---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql
  namespace: langflow
spec:
  serviceName: postgresql-svc
  replicas: 1
  selector:
    matchLabels:
      app: langflow-postgres
  template:
    metadata:
      labels:
        app: langflow-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
              name: postgres
          env:
            # Configura las credenciales iniciales alineadas con tu Langflow
            - name: POSTGRES_USER
              value: "langflow"
            - name: POSTGRES_DB
              value: "langflow-db"
            - name: POSTGRES_PASSWORD
              value: "langflow1234" 
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
  
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 5Gi