apiVersion: ENC[AES256_GCM,data:9mU=,iv:P1gd2lvGZKSjZDOWbhP/2m+zuwQ0ug6XYSkJu7+3EHU=,tag:jsk5ahadalTQv/WXuFYaOQ==,type:str]
kind: ENC[AES256_GCM,data:H1Tp0ldx,iv:s8yDhwvpli2gIQvONsfuUQypYqxIPikDp675r2HmVEA=,tag:sztxvkKG+GEzoQT1MEw+UQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:e2iDwjQ+wR5sDOi5E8iJlw==,iv:rK8Cp6uWh3YeVxmyHWhzkVX6xDy/3KA93lTbTYcjeo4=,tag:kPE/zT+smxDFSg8ig2kd2A==,type:str]
    namespace: ENC[AES256_GCM,data:t3OZqJ16BMw=,iv:NU2KcF9Wch15W3SacQpkeltGqQqURhSbvJ+1IwlA/wY=,tag:3o35kpS2PtHCu/N1ISBPkg==,type:str]
type: ENC[AES256_GCM,data:Q/q//kYi,iv:FF5O8eA4MsGrj6g4pXS+8NBTyW4ntkFgSJlKd8h0JI8=,tag:HbHQMW7rnwz0LAOTlOggPw==,type:str]
data:
    DB_PASSWORD: ENC[AES256_GCM,data:7V5NyUdlYzSy5GaF,iv:0/UFbBHtL9+b9iWqW9mjZuKDDEckW/GK5PGH5Tu8ohg=,tag:jEiT+hmTltTNCUuzXXj9cg==,type:str]
    postgres-password: ENC[AES256_GCM,data:4o3QoyZGO842vqtx,iv:AUo5IgpWbciy4Y14Nu3PtMEQnFXnDdZCNQQBdk20mhY=,tag:YVjVA2/I0y7tw+2VKjrFUA==,type:str]
sops:
    age:
        - recipient: age1dcjryzpfkrpr82lcjh7twese80g0wcqe5c5mhqmkkry7xj5ar46stjq8xk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvT3VRd2FBbFVJZVQrYVM0
            WXgvNkRSUEJZajI1SFpkSk4xRUx1WXNlaUFrCnMwcUsxN3VNcWJnVGpkQnB2Y25j
            bWg4TVlGRThkeG5LbDhRVUFzNWMzMVUKLS0tIDYzTTNQanBKYktXbHhrU0s2SFF6
            UFVvNHgvMi9HUmhlOE5QQ0hHdlNPNjAKY60DpL5IRzq2/Thxm0AZD/1NVM3PxUWI
            5eCH29UmtNXXwvJ1AdILDZDjfdUTvSaZwUt84erGyGcYzCfKXqbRbA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-11T11:54:58Z"
    mac: ENC[AES256_GCM,data:cgBydqLz913j6meh8/pVF65CiEiBo7mHj4o/rCA0MQfLC5m1zdZZDoMyzdkESjDHTKB83lbiXlkxxcsn0dydOtaHIkuCbLghSFlYCsMdFbnQqSq+dX12vTa+kXJ5+/1k8x37Gdc4l7MxR/trBdLtH1NbqK3aF+JdycelAKitqgU=,iv:WSC7whvVgZbMhG3OPtQPjbZZqIFwEVBrNe95p/vsawI=,tag:eONK/N+IGQd+hZgNhhCn7A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
