apiVersion: ENC[AES256_GCM,data:WRU=,iv:pgBKmjLkmcd7XUQoQDAGaALfZDyJ2q+Eb/AvTevK3o4=,tag:Ucs/YRJBzmPU1TmJOdnXMQ==,type:str]
kind: ENC[AES256_GCM,data:i7R79kEA,iv:5sm4Vrdxd7T9LGmiJRZFxBWOfrYJ881chWDVy6SY63Y=,tag:5o9CBNiNM2kCr7p30n+cmw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:fxYXuOmO0IYqPY+WmfOW7A==,iv:iNeGo8t0VQWHxAv4mCBx3HEj7NBVRPI+DJpZmyKSPaM=,tag:Cv/EuNn8xHxACKgUr09V/A==,type:str]
    namespace: ENC[AES256_GCM,data:hSC/8DjSsv8=,iv:q0vFZ+YVP2f+7KPUJS56tkv0d+uw7r7TG7RYqBOeyTk=,tag:0OLqM8iMqK7mrVTPT1Jheg==,type:str]
type: ENC[AES256_GCM,data:TvwFXjzp,iv:X+1qsOU2K4BFO0krhF9+vDwmjIft7KnJnjzygpmmvKE=,tag:rwV7+upz+zgXAtY8YbUn1g==,type:str]
stringData:
    DB_PASSWORD: ENC[AES256_GCM,data:xsp6endoN/nkOVCA,iv:GgL9U12o1CQEo1MMnbXVD4IPZjo0wEbdKeKbI8htwTo=,tag:52BLrU8ETdCa3zvridHuBA==,type:str]
    postgres-password: ENC[AES256_GCM,data:C9OWYfGhfQbqblMn,iv:SsexN4PPk2vgoyqh0tjnWpiJ48n4/V6k9U38Nhgvymo=,tag:udAQrjR4pDW0cygJLsa2Ew==,type:str]
sops:
    age:
        - recipient: age1dcjryzpfkrpr82lcjh7twese80g0wcqe5c5mhqmkkry7xj5ar46stjq8xk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3Smh2NTllTk5yNGFoM2hH
            NEF2NkM0cnFYWnQxbTllYjIzWEpmdnJrL1dNCm92aTRreHFtYmlCdURRWHF1Vm1C
            Y0Nad1BoOU9RR3NIbUFpNkpPTzRTY2sKLS0tIGZ5YmVIZWpSU2kzbmdnQlRQazFN
            WGdsNEcxZlVYR0xZdHd5MGIvR2lSMFEKWyd8XKSIGhE8UNigD9WhgvYmDqzjLo7G
            6bK1B/HOapCJ3q24MS88HQ9SJxjrsZ9n3PIZ+/YPNiDlxIzck5SOVA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-11T13:17:40Z"
    mac: ENC[AES256_GCM,data:Nikc+BoNiUCjFnM3ZozeGews2mCOrruvMchylrBOhysYUbuwveI+C+nQwawqVmXjdNQQo+Mb5BB9h/9zgshYpzWodeDHY1iJHgn7gQRuKUiBS9pHKsMZdP2kGvl/PmO0n91PpLFxU7npoihn/I3+HyUWJSQarlHV7VXbMestM2Y=,iv:1KGdg3SZA3z09LJ5ytvcGkzf1bSvFFIZrclwL9sspW0=,tag:TSWPti4139tMXqUCNC6RhQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
