apiVersion: ENC[AES256_GCM,data:eog=,iv:GdoATarLIR9AQXYVkHRtxyDKrABejtFS+igMD0lTzkk=,tag:QzF0VbmuW2zrPL2tS9RlNA==,type:str]
kind: ENC[AES256_GCM,data:0zSQsqdP,iv:Nt7T5Ypw/i5RUAepigih1L0aZrYdl4imU5X8299gGVo=,tag:kjaBZ7F86o9Niw0rHLNUrw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:KCxkgpZzjFDndAWWPWBntQ==,iv:X8AuCoUDEEnAlaDcoYHX4aSqHvUPpDeOalztWAhUpoQ=,tag:kQTYjmNhTS0EoDgJN+Hi7Q==,type:str]
    namespace: ENC[AES256_GCM,data:IpwPC/+SwI8=,iv:JpCplEAcrXKJuQuDwAWuBRmQfddFMzBGqcJPRJ9+mn8=,tag:zS7rw8c/Wpw8+O1zw3qQxQ==,type:str]
type: ENC[AES256_GCM,data:o31d7rl5,iv:Hbl1Lf4SapM78hj8P36je3tvuw8lHM8nTzeSFlSxuNQ=,tag:Ojsk7QsyvYZNHonEptaRtQ==,type:str]
stringData:
    DB_PASSWORD: ENC[AES256_GCM,data:+qU3RNph5d5QIMy3,iv:Z+iUlfvqWCSXOz6usYImiJqWYD/ZY2SRAZ/L4sMs4ek=,tag:H5UNHGbVIW3O2xNfm+x8VA==,type:str]
    postgres-password: ENC[AES256_GCM,data:RrfYq7+B0sR4NaXx,iv:yYaS4561msllCwSwWBG63AnfvTUwsuAxz3vdIvFc4Ps=,tag:i8qT7qoTWLqNf7aoSadZcw==,type:str]
sops:
    age:
        - recipient: age1dcjryzpfkrpr82lcjh7twese80g0wcqe5c5mhqmkkry7xj5ar46stjq8xk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6Z3ZwaHdCMFNqRVlwZVMx
            eFF6all6VHhqcEVlcCtVRjFTcVorcEJ4ejJvCmVTNVo0SDFadHA4T0hqeDBtYzZR
            akVjdkE5RnVmYitJdWZ3aGQ0YTVpUlUKLS0tIG1pQ01WQmo0c2lvRnMyYm83VFJY
            WEpHSnNpRkc4M3k3cXZFMzlSdzEza2cKcxdUHk/72bEWeSEPSgOrpXDlg5K7cj3d
            yxPjZRRMvjj9+LsRy6ZYD23iGmJSt2TEnXhEpr1G1A22TP+Rz7jmbA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-11T11:39:36Z"
    mac: ENC[AES256_GCM,data:YVc+hczNwKKFCx1cy6Door7KShkHPCZZRCOj1RUNFnqlCiHzjGZT4tYY6wIoKZeDFC00cJ2ldLGUPtXYc6PU+Z3YYAiCUfW9KxaQWxwzcEGDU0tBhZ6vDwrgt6P+ipRa2PPmeILIe3IVQFIIKfMEuqIOr9ttsTsA6YeFXXdL9eE=,iv:j2W7X6sxEq8dx6M68hxlnCZVtjrMIG6fj3SU7aG0jQ4=,tag:KILMu08pKMip9HpMkW1Qlw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
