apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: langflow
  namespace: langflow
spec:
  interval: 5m
  timeout: 30m
  chart:
    spec:
      chart: langflow-ide
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: langflow
        namespace: flux-system
  install:
    createNamespace: true
  upgrade:
    remediation:
      retries: 3

  values:
    # 1. Configuración de Langflow
    langflow:
      global:
        image:
          tag: "latest"

      backend:
        replicaCount: 1
        livenessProbe:
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          initialDelaySeconds: 60
          periodSeconds: 10
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            cpu: 3
            memory: 3Gi
        env:
          - name: LANGFLOW_LOG_LEVEL
            value: "INFO"
          - name: LANGFLOW_ALEMBIC_LOG_FILE
            value: "/tmp/alembic.log"
        autoLogin: false
        superuser: "jorge"                      
        superuserPassword: "jorge1234"

        sqlite:
          enabled: false

        externalDatabase:
          enabled: true
          driver:
            value: "postgresql"
          host:
            value: "postgresql-svc.langflow.svc.cluster.local"
          port:
            value: "5432"
          user:
            value: "langflow"
          database:
            value: "langflow"
          password:
            value: "langflow1234"

      frontend:
        replicaCount: 1
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 1
            memory: 1Gi

    # 2. Subchart de PostgreSQL (Alineado a la raíz de values)
    postgresql:
      enabled: false
        
      resources:
        requests:
          cpu: 250m
          memory: 512Mi
        limits:
          cpu: 1
          memory: 2Gi
      primary:
        extraVolumes:
          - name: postgres-run
            emptyDir: {}
        extraVolumeMounts:
          - name: postgres-run
            mountPath: /var/run/postgresql
      persistence:
        enabled: false
      securityContext:
        fsGroup: 1001

    # 3. Persistencia General (Alineado a la raíz de values)
    persistence:
      enabled: true
      volumes:
        flows:
          enabled: true
        data:
          enabled: true
        db:
          enabled: false

    # 4. Ingress (Alineado a la raíz de values)
    ingress:
      enabled: true
      className: nginx
      hosts:
        - host: langflow.local
          paths:
            - path: /
              pathType: Prefix